### ISSUE TITLE
CartoCSS conditional styling

### ISSUE THREAD

**Issue by eightysteele** [MapofLife/MOL#71]
We need styling rules from @robgur and @walterj for layers. Those rules will get encoded in CartoCSS on our CartoDB instance.

**Comment by walterj** [comment]
For now (beta release) I propose the following default styling for expert range maps.

Default field displayed is' Seasonality'. 
Default styles are: 1 = Resident = green; 2 = Breeding only = yellow; 3 = Non-breeding = blue; 4 = Passage = light blue; 5 and others = blue green

Will we allow toggling to a different field for display (e.g. ORIGIN) and if so, would the same color-number connection be enforced, or could we set up a different default for specific fields?

**Comment by eightysteele** [comment]
For the beta release, lets go with Carto styling on the `seasonality` column using the following rules you defined:

```
1 = Resident = green 
2 = Breeding only = yellow
3 = Non-breeding = blue
4 = Passage = light blue
5 and others = blue green
```

After the release, we can definitely explore support for toggling different styling rules (e.g., for the `origin` column) using the `style` URL parameter for tile requests.

**Comment by robgur** [comment]
+1

**Comment by gaurav** [comment]
As per e-mail conversations, we'd like to have different species visually differentiated on the UI. So, for instance, if there are two species, they should use two different shades of green for resident areas, two different shades for yellow for breeding only, and so on.

**Comment by eightysteele** [comment]
We probably won't have time for this before the release, but let's definitely revisit this in #87.

**Comment by eightysteele** [comment]
Done with the following Carto:

``` css
#polygons_new{
   polygon-fill:#FF6600;
   line-color:#FFFFFF;
   line-width:0;
   polygon-opacity:0.43;
   line-opacity:0.43;
   [seasonality=1]{
   polygon-fill:#99CC00}
[seasonality=2]{
   polygon-fill:#FFCC00}
[seasonality=3]{
   polygon-fill:#006BB4}
[seasonality=4]{
   polygon-fill:#FF9900}
[seasonality=5]{
   polygon-fill:#E25B5B}
}
```

Closing issue.

**Comment by robgur** [comment]
We need a way to provide a table legend for these stylings so people understand what the coloration means.  For next deadline March 6th?

**Comment by walterj** [comment]
Still can't see them. Can anyone give an example that works?

-----Original Message-----

**Comment by eightysteele** [comment]
@robgur - I'll add a task to BC.

@walter - The Carto update is on our new polygon table that isn't yet wired into the UI. We're waiting for bulkloading to finish up.

**Comment by robgur** [comment]
changing transparency resets color to "green" from whatever style it has (on Chrome)

**Comment by eightysteele** [comment]
Yep good catch. It's a quick fix, we just need to filter polygon coloring in the `style` parameter of the tile request.
