### ISSUE TITLE
Add icons to layer widgets

### ISSUE THREAD

**Issue by eightysteele** [MapofLife/MOL#74]
Similar to #43, but for the layer widgets, not the search widgets. Right now we have the type icon, but we're missing the source icon.

**Comment by robgur** [comment]
Is this just missing or in need of a new design?

**Comment by eightysteele** [comment]
Just missing, exactly as it was in #43.

**Comment by jmalczyk** [comment]
Fixed in 63ced7e811463b13b1421b77e79b7a06c278c4b8

**Comment by eightysteele** [comment]
Re-opening issue. They are still missing as of 63ced7e. Did you add the icons to the repo?

**Comment by eightysteele** [comment]
Fixed. Closing issue.
